/**
 * Realistic Fictional Indian School Mock Data for SchoolERP
 * Aligned with Stitch UI references & PRD requirements
 */

export const INITIAL_SCHOOL_SETTINGS = {
  schoolName: 'Vidya Mandir Academy',
  tagline: 'Early Years Edition',
  academicYear: '2026–27',
  schoolAddress: 'Plot 42, Sector 14, Palm Beach Road, Navi Mumbai, MH 400705',
  phone: '+91 98200 12345',
  email: 'contact@vidyamandir.edu.in',
  campusName: 'Oakridge Campus',
  activeTerm: 'Term 2 (Spring)',
  adminName: 'Rajesh Verma',
  adminEmail: 'admin@schoolerp.in',
  adminRole: 'Super Admin',
};

export const INITIAL_CLASSES = [
  { id: 'cls-1', name: 'Nursery A', classLevel: 'Nursery', section: 'A', academicYear: '2026–27', teacherName: 'Pooja Sharma', capacity: 22, studentCount: 22, status: 'Active', annualFee: 25000 },
  { id: 'cls-2', name: 'Nursery B', classLevel: 'Nursery', section: 'B', academicYear: '2026–27', teacherName: 'Sunita Rao', capacity: 20, studentCount: 20, status: 'Active', annualFee: 25000 },
  { id: 'cls-3', name: 'Jr KG A', classLevel: 'Junior KG', section: 'A', academicYear: '2026–27', teacherName: 'Kavita Joshi', capacity: 22, studentCount: 22, status: 'Active', annualFee: 30000 },
  { id: 'cls-4', name: 'Jr KG B', classLevel: 'Junior KG', section: 'B', academicYear: '2026–27', teacherName: 'Meenakshi Iyer', capacity: 21, studentCount: 21, status: 'Active', annualFee: 30000 },
  { id: 'cls-5', name: 'Sr KG A', classLevel: 'Senior KG', section: 'A', academicYear: '2026–27', teacherName: 'Anjali Deshmukh', capacity: 22, studentCount: 22, status: 'Active', annualFee: 32000 },
  { id: 'cls-6', name: 'Sr KG B', classLevel: 'Senior KG', section: 'B', academicYear: '2026–27', teacherName: 'Neha Kulkarni', capacity: 21, studentCount: 21, status: 'Active', annualFee: 32000 },
  { id: 'cls-7', name: 'Grade 1 A', classLevel: 'Grade 1', section: 'A', academicYear: '2026–27', teacherName: 'Sanjay Gupta', capacity: 25, studentCount: 20, status: 'Active', annualFee: 35000 },
  { id: 'cls-8', name: 'Playgroup Alpha', classLevel: 'Playgroup', section: 'Alpha', academicYear: '2026–27', teacherName: 'Radha Menon', capacity: 15, studentCount: 0, status: 'Inactive', annualFee: 20000 },
];

export const INITIAL_PARENTS = [
  { id: 'par-1', fullName: 'Suresh Sharma', phone: '+91 98201 11223', email: 'suresh.sharma@example.com', address: 'B-402, Green Valley Heights, Sector 14, Navi Mumbai', occupation: 'Software Consultant', studentsCount: 1 },
  { id: 'par-2', fullName: 'Ganesh Patil', phone: '+91 98192 33445', email: 'ganesh.patil@example.com', address: 'A-101, Om Residency, Vashi, Navi Mumbai', occupation: 'Civil Engineer', studentsCount: 1 },
  { id: 'par-3', fullName: 'Anand Kulkarni', phone: '+91 98334 55667', email: 'anand.k@example.com', address: 'Flat 6B, Seawoods Palms, Seawoods, Navi Mumbai', occupation: 'Chartered Accountant', studentsCount: 1 },
  { id: 'par-4', fullName: 'Deepak Joshi', phone: '+91 98700 88991', email: 'deepak.joshi@example.com', address: 'Row House 12, NRI Complex, Nerul, Navi Mumbai', occupation: 'Business Owner', studentsCount: 1 },
  { id: 'par-5', fullName: 'Ramesh Mehta', phone: '+91 98201 44521', email: 'ramesh.mehta@example.com', address: 'C-703, Harmony Towers, Koparkhairane, Navi Mumbai', occupation: 'Architect', studentsCount: 1 },
  { id: 'par-6', fullName: 'Sunita Deshmukh', phone: '+91 97654 33210', email: 'sunita.deshmukh@example.com', address: 'D-201, Sunshine Park, Kharghar, Navi Mumbai', occupation: 'Doctor (Pediatrician)', studentsCount: 1 },
  { id: 'par-7', fullName: 'Vikram Rao', phone: '+91 98812 77410', email: 'vikram.rao@example.com', address: 'Flat 502, Blue Diamond, Belapur, Navi Mumbai', occupation: 'Financial Analyst', studentsCount: 1 },
  { id: 'par-8', fullName: 'Rajesh Nair', phone: '+91 98450 12345', email: 'rajesh.nair@example.com', address: '12-A, Palm Greens, Sanpada, Navi Mumbai', occupation: 'Banker', studentsCount: 1 },
  { id: 'par-9', fullName: 'Amit Gupta', phone: '+91 97110 54321', email: 'amit.gupta@example.com', address: 'B-12, Sagar Darshan, Vashi, Navi Mumbai', occupation: 'Corporate Lawyer', studentsCount: 1 },
  { id: 'par-10', fullName: 'Subhash Sen', phone: '+91 98310 99887', email: 'subhash.sen@example.com', address: 'E-304, Royal Palms, Airoli, Navi Mumbai', occupation: 'Professor', studentsCount: 1 },
];

export const INITIAL_STUDENTS = [
  {
    id: 'stu-1',
    studentId: 'STU-2026-001',
    firstName: 'Aarav',
    lastName: 'Sharma',
    dateOfBirth: '2021-08-14',
    gender: 'Male',
    classId: 'cls-3',
    className: 'Jr KG A',
    parentId: 'par-1',
    parentName: 'Suresh Sharma',
    phone: '+91 98201 11223',
    email: 'suresh.sharma@example.com',
    address: 'B-402, Green Valley Heights, Sector 14, Navi Mumbai',
    admissionDate: '2026-06-05',
    totalFee: 30000,
    paidFee: 20000,
    pendingFee: 10000,
    feeStatus: 'Pending',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAGj3Edi-LfByP0PQOScwJLHNk16-pjmXGfIblWPNhJK_AdKUOHSp5nkUlgfFnDvVgfoyJxb0zbE2Qj-flx8RIcE24g4lFlOZjJsMFtuMtRXk6jb471cIDYRQcfVJLJwVf7NojnqBNXcJoJEpOE5zS15K2qqQIdR0caBlWytiMfDnKqb82M3mehOrx2ZzKnsKWjb9vDN92v6HSf23lHN_mcEq0aRrwrvdj1JgxfknA50_RLcNcuz6Z8',
  },
  {
    id: 'stu-2',
    studentId: 'STU-2026-002',
    firstName: 'Anaya',
    lastName: 'Patil',
    dateOfBirth: '2022-11-19',
    gender: 'Female',
    classId: 'cls-1',
    className: 'Nursery A',
    parentId: 'par-2',
    parentName: 'Ganesh Patil',
    phone: '+91 98192 33445',
    email: 'ganesh.patil@example.com',
    address: 'A-101, Om Residency, Vashi, Navi Mumbai',
    admissionDate: '2026-06-02',
    totalFee: 25000,
    paidFee: 25000,
    pendingFee: 0,
    feeStatus: 'Clear',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvqjCPQzF7uEPTsG7Sx_c0cBovddXdpHiJA-70KBV6v0G9cLdCt3EgGWOSdm98nz2A9fL3wsyboM_BjDyavrpRiT5o3tGMrJR1xF2qgJZPi9Rg23z0IMeJKJ3XKcW-5RDLHJtYAm_QtLtwpisRBAswnUxGPmThlea0EzBbqW2Ei3GjEqukc7MqZFDZEZCLk93ZQReiVVkIyD1jDhjGbqGThlBQ1KuihReZH5PJ0Aaqdt-489TjFI6r',
  },
  {
    id: 'stu-3',
    studentId: 'STU-2026-003',
    firstName: 'Vivaan',
    lastName: 'Kulkarni',
    dateOfBirth: '2020-03-23',
    gender: 'Male',
    classId: 'cls-6',
    className: 'Sr KG B',
    parentId: 'par-3',
    parentName: 'Anand Kulkarni',
    phone: '+91 98334 55667',
    email: 'anand.k@example.com',
    address: 'Flat 6B, Seawoods Palms, Seawoods, Navi Mumbai',
    admissionDate: '2026-06-08',
    totalFee: 32000,
    paidFee: 32000,
    pendingFee: 0,
    feeStatus: 'Clear',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFXEzP0XhgjMeTaZiabvv5uRbJyO0m_nSwVOfTLKlyDjW6pNLKz0tmHBbzbapDlXWH3k2T8SclSUAwXijR1COZmnSIf6G2faqouwCNZwyX3rzQQVhsC7qUTY_01SiSue2vG8ltPK1Z2TQ6Bv7mFVTxf40e8fd5C3qI5bwfLFpdj2uaS2Cb17Dvr8nX2_MOwTE4fI3cE1b8-fpv108BOfucJPKiAAnm4h31Oy2iwFBwuSd9MU_OAx9o',
  },
  {
    id: 'stu-4',
    studentId: 'STU-2026-004',
    firstName: 'Myra',
    lastName: 'Joshi',
    dateOfBirth: '2021-01-12',
    gender: 'Female',
    classId: 'cls-4',
    className: 'Jr KG B',
    parentId: 'par-4',
    parentName: 'Deepak Joshi',
    phone: '+91 98700 88991',
    email: 'deepak.joshi@example.com',
    address: 'Row House 12, NRI Complex, Nerul, Navi Mumbai',
    admissionDate: '2026-06-10',
    totalFee: 30000,
    paidFee: 26000,
    pendingFee: 4000,
    feeStatus: 'Pending',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQPQYle9sp_7_2wyM5aMm3wwYnthZG3iTmrbKr5JgkCKH3TNjyqhI42qoEo6hp5hse5mcm32sAI98lOSLAs-6RbBaZAS7_98TjUa7FbGMj_xVlDngAEi12DeU0jpAR2OFTv4zoaAiPPs7rfCa-D2w3DPI6uBZH2CILCbjX47Rr8wAsjbUC6FIiYgkfwJ9cpMa59lg6o8qDLJjY-F1i5mGliZk5o_Ugf_qt79MelfejOg4Ax5AL7pL3',
  },
  {
    id: 'stu-5',
    studentId: 'STU-2026-005',
    firstName: 'Kabir',
    lastName: 'Mehta',
    dateOfBirth: '2022-05-04',
    gender: 'Male',
    classId: 'cls-2',
    className: 'Nursery B',
    parentId: 'par-5',
    parentName: 'Ramesh Mehta',
    phone: '+91 98201 44521',
    email: 'ramesh.mehta@example.com',
    address: 'C-703, Harmony Towers, Koparkhairane, Navi Mumbai',
    admissionDate: '2026-06-12',
    totalFee: 25000,
    paidFee: 10000,
    pendingFee: 15000,
    feeStatus: 'Pending',
    status: 'Active',
    avatar: null,
  },
  {
    id: 'stu-6',
    studentId: 'STU-2026-006',
    firstName: 'Rhea',
    lastName: 'Deshmukh',
    dateOfBirth: '2020-10-18',
    gender: 'Female',
    classId: 'cls-5',
    className: 'Sr KG A',
    parentId: 'par-6',
    parentName: 'Sunita Deshmukh',
    phone: '+91 97654 33210',
    email: 'sunita.deshmukh@example.com',
    address: 'D-201, Sunshine Park, Kharghar, Navi Mumbai',
    admissionDate: '2026-06-15',
    totalFee: 32000,
    paidFee: 18000,
    pendingFee: 14000,
    feeStatus: 'Pending',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEjbgAKChXzGs_KNx6IbqnuDv1trcHyDmKGq8js1Ko6hZkLJ0_iC6kSpszbyWnx9HtKtVS2nWBwsdH-nWT_F6u78zyMIAm8tKXmpH1Udp2nRFStZb7VZhRElsbN_eYBdLcQeOrGOkdZ4SwLtg0HgDsf8TCJeuanNSADVAo4k0VYng90bUjjJlxTbUmkrkwLrxwKw13_nYQrXZojwTQZ7eYs92ipfufzu-fO-T6t0LgwjJRsLfkn8SV',
  },
  {
    id: 'stu-7',
    studentId: 'STU-2026-007',
    firstName: 'Advait',
    lastName: 'Rao',
    dateOfBirth: '2021-09-02',
    gender: 'Male',
    classId: 'cls-3',
    className: 'Jr KG A',
    parentId: 'par-7',
    parentName: 'Vikram Rao',
    phone: '+91 98812 77410',
    email: 'vikram.rao@example.com',
    address: 'Flat 502, Blue Diamond, Belapur, Navi Mumbai',
    admissionDate: '2026-06-18',
    totalFee: 30000,
    paidFee: 18000,
    pendingFee: 12000,
    feeStatus: 'Pending',
    status: 'Active',
    avatar: null,
  },
  {
    id: 'stu-8',
    studentId: 'STU-2026-008',
    firstName: 'Ishita',
    lastName: 'Sen',
    dateOfBirth: '2022-02-11',
    gender: 'Female',
    classId: 'cls-1',
    className: 'Nursery A',
    parentId: 'par-10',
    parentName: 'Subhash Sen',
    phone: '+91 98310 99887',
    email: 'subhash.sen@example.com',
    address: 'E-304, Royal Palms, Airoli, Navi Mumbai',
    admissionDate: '2026-06-20',
    totalFee: 25000,
    paidFee: 25000,
    pendingFee: 0,
    feeStatus: 'Clear',
    status: 'Inactive',
    avatar: null,
  },
  {
    id: 'stu-9',
    studentId: 'STU-2026-009',
    firstName: 'Diya',
    lastName: 'Nair',
    dateOfBirth: '2020-10-18',
    gender: 'Female',
    classId: 'cls-5',
    className: 'Sr KG A',
    parentId: 'par-8',
    parentName: 'Rajesh Nair',
    phone: '+91 98450 12345',
    email: 'rajesh.nair@example.com',
    address: '12-A, Palm Greens, Sanpada, Navi Mumbai',
    admissionDate: '2026-06-15',
    totalFee: 32000,
    paidFee: 32000,
    pendingFee: 0,
    feeStatus: 'Clear',
    status: 'Active',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBEjbgAKChXzGs_KNx6IbqnuDv1trcHyDmKGq8js1Ko6hZkLJ0_iC6kSpszbyWnx9HtKtVS2nWBwsdH-nWT_F6u78zyMIAm8tKXmpH1Udp2nRFStZb7VZhRElsbN_eYBdLcQeOrGOkdZ4SwLtg0HgDsf8TCJeuanNSADVAo4k0VYng90bUjjJlxTbUmkrkwLrxwKw13_nYQrXZojwTQZ7eYs92ipfufzu-fO-T6t0LgwjJRsLfkn8SV',
  },
  {
    id: 'stu-10',
    studentId: 'STU-2026-010',
    firstName: 'Reyansh',
    lastName: 'Gupta',
    dateOfBirth: '2021-09-02',
    gender: 'Male',
    classId: 'cls-3',
    className: 'Jr KG A',
    parentId: 'par-9',
    parentName: 'Amit Gupta',
    phone: '+91 97110 54321',
    email: 'amit.gupta@example.com',
    address: 'B-12, Sagar Darshan, Vashi, Navi Mumbai',
    admissionDate: '2026-06-18',
    totalFee: 30000,
    paidFee: 30000,
    pendingFee: 0,
    feeStatus: 'Clear',
    status: 'Active',
    avatar: null,
  },
];

export const INITIAL_PAYMENTS = [
  {
    id: 'pay-1',
    receiptNumber: 'REC-1048',
    studentId: 'stu-1',
    studentName: 'Aarav Sharma',
    className: 'Jr KG A',
    amount: 5000,
    paymentDate: '2026-09-22',
    paymentMode: 'UPI',
    status: 'Paid',
    notes: 'Q2 Tuition Installment',
  },
  {
    id: 'pay-2',
    receiptNumber: 'REC-1047',
    studentId: 'stu-2',
    studentName: 'Anaya Patil',
    className: 'Nursery A',
    amount: 8000,
    paymentDate: '2026-09-22',
    paymentMode: 'Cash',
    status: 'Paid',
    notes: 'Full Clearance Balance',
  },
  {
    id: 'pay-3',
    receiptNumber: 'REC-1046',
    studentId: 'stu-3',
    studentName: 'Vivaan Kulkarni',
    className: 'Sr KG B',
    amount: 6500,
    paymentDate: '2026-09-21',
    paymentMode: 'Bank Transfer',
    status: 'Paid',
    notes: 'Term 2 Final Settlement',
  },
  {
    id: 'pay-4',
    receiptNumber: 'REC-1045',
    studentId: 'stu-4',
    studentName: 'Myra Joshi',
    className: 'Jr KG B',
    amount: 4000,
    paymentDate: '2026-09-21',
    paymentMode: 'UPI',
    status: 'Paid',
    notes: 'Partial Payment',
  },
  {
    id: 'pay-5',
    receiptNumber: 'REC-1044',
    studentId: 'stu-7',
    studentName: 'Advait Rao',
    className: 'Jr KG A',
    amount: 10000,
    paymentDate: '2026-09-18',
    paymentMode: 'Bank Transfer',
    status: 'Paid',
    notes: 'Term 1 Balance',
  },
  {
    id: 'pay-6',
    receiptNumber: 'REC-1043',
    studentId: 'stu-6',
    studentName: 'Rhea Deshmukh',
    className: 'Sr KG A',
    amount: 8000,
    paymentDate: '2026-09-15',
    paymentMode: 'UPI',
    status: 'Paid',
    notes: 'September Fee Installment',
  },
  {
    id: 'pay-7',
    receiptNumber: 'REC-1042',
    studentId: 'stu-5',
    studentName: 'Kabir Mehta',
    className: 'Nursery B',
    amount: 10000,
    paymentDate: '2026-09-12',
    paymentMode: 'Cash',
    status: 'Paid',
    notes: 'Initial Admission Fee Token',
  },
];

export const INITIAL_FEE_STRUCTURES = [
  { id: 'fs-1', classId: 'cls-1', className: 'Nursery A', academicYear: '2026–27', annualFee: 25000, status: 'Active' },
  { id: 'fs-2', classId: 'cls-2', className: 'Nursery B', academicYear: '2026–27', annualFee: 25000, status: 'Active' },
  { id: 'fs-3', classId: 'cls-3', className: 'Jr KG A', academicYear: '2026–27', annualFee: 30000, status: 'Active' },
  { id: 'fs-4', classId: 'cls-4', className: 'Jr KG B', academicYear: '2026–27', annualFee: 30000, status: 'Active' },
  { id: 'fs-5', classId: 'cls-5', className: 'Sr KG A', academicYear: '2026–27', annualFee: 32000, status: 'Active' },
  { id: 'fs-6', classId: 'cls-6', className: 'Sr KG B', academicYear: '2026–27', annualFee: 32000, status: 'Active' },
  { id: 'fs-7', classId: 'cls-7', className: 'Grade 1 A', academicYear: '2026–27', annualFee: 35000, status: 'Active' },
];

export const INITIAL_ATTENDANCE_SNAPSHOT = {
  date: '2026-09-22',
  total: 128,
  present: 115,
  absent: 13,
  classBreakdown: [
    { className: 'Nursery A', present: 20, total: 22, percentage: 90.9 },
    { className: 'Nursery B', present: 19, total: 20, percentage: 95.0 },
    { className: 'Jr KG A', present: 21, total: 22, percentage: 95.4 },
    { className: 'Jr KG B', present: 19, total: 21, percentage: 90.4 },
    { className: 'Sr KG A', present: 20, total: 22, percentage: 90.9 },
    { className: 'Sr KG B', present: 16, total: 21, percentage: 76.1 },
  ],
  studentRecords: {
    '2026-09-22': {
      'stu-1': 'Present',
      'stu-2': 'Present',
      'stu-3': 'Present',
      'stu-4': 'Present',
      'stu-5': 'Absent',
      'stu-6': 'Present',
      'stu-7': 'Present',
      'stu-8': 'Absent',
      'stu-9': 'Present',
      'stu-10': 'Present',
    },
  },
};
